#!/usr/bin/env python

import sys

from impl.tools import clean_multipart_uploads

for s3_bucket in sys.argv[1:]:
    print(f'Cleaning multipart uploads for bucket {s3_bucket}')
    clean_multipart_uploads(s3_bucket)
