#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "Usage: ./expire SETTINGS_FILE BACKUPS_TO_KEEP"
    echo "  Example: ./expire config/backup.sh 10"
    exit 1
fi

SETTINGS=$1
DELETE_FROM_LINE=$(($2+1))

# shellcheck disable=SC1090
source "$SETTINGS"

URL="s3://$S3_BUCKET"
if [[ -n "$BUCKET_DIR" ]]; then
    URL="$URL/$BUCKET_DIR"
fi

entries=$(aws s3 ls --no-paginate "$URL/" | sort -r | tail -n "+$DELETE_FROM_LINE" | sed "s#.*PRE #$URL/#g")
if [[ -z "$entries" ]]; then
    exit 0
fi

echo "Deleting these entries:"
echo "$entries"

if [[ -v PS1 ]]; then
    read -p "Are you sure? " -n 1 -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo "$entries" | xargs -I "{}" --no-run-if-empty aws s3 rm "{}" --recursive
